# Site settings
title: Pharmbot
subtitle: At the intersection between programming and pharmacology.
email: eclay101@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.emlynclay.co.uk" # the base hostname & protocol for your site
twitter_username: emlynclay
github_username:  emlync

# Build settings
markdown: kramdown
